java_import(
    name = "tools",
    jars = ["@bazel_tools//tools/jdk:langtools"],
)

java_library(
    name = "meghanada-server-lib",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/*"]),
    runtime_deps = [
        "//external:android-gradle-api-jar",
        "//external:hamcrest-core-jar",
        "//external:minlog-jar",
        "//external:objenesis-jar",
        "//external:reflectasm-jar",
        "//external:slf4j-api-jar",
    ],
    deps = [
        ":tools",
        "//external:android-builder-model-jar",
        "//external:asm-jar",
        "//external:commons-cli-jar",
        "//external:commons-lang3-jar",
        "//external:config-jar",
        "//external:evo-inflector-jar",
        "//external:gradle-tooling-api-jar",
        "//external:guava-jar",
        "//external:javaparser-core-jar",
        "//external:junit-jar",
        "//external:kryo-jar",
        "//external:log4j-api-jar",
        "//external:log4j-core-jar",
        "//external:log4j-slf4j-impl-jar",
        "//external:maven-model-jar",
        "//external:motif-hamcrest-jar",
        "//external:motif-jar",
        "//external:plexus-utils-jar",
        "//external:roaster-api-jar",
        "//external:roaster-jdt-jar",
        "//external:zstd-jni-jar",
    ],
)

java_binary(
    name = "server",
    main_class = "meghanada.Main",
    runtime_deps = [":meghanada-server-lib"],
)

java_test(
    name = "tests",
    size = "small",
    srcs = glob(["src/test/java/**/*.java"]),
    data = glob([
        "src/main/java/**/*.java",
        "src/test/java/**/*.java",
        "src/test/resources/*",
    ]),
    local = 1,
    resources = glob(["src/test/resources/*"]),
    test_class = "meghanada.AllTests",
    deps = [
        ":meghanada-server-lib",
        ":tools",
        "//external:android-builder-model-jar",
        "//external:asm-jar",
        "//external:commons-cli-jar",
        "//external:commons-lang3-jar",
        "//external:config-jar",
        "//external:evo-inflector-jar",
        "//external:gradle-tooling-api-jar",
        "//external:guava-jar",
        "//external:javaparser-core-jar",
        "//external:junit-jar",
        "//external:kryo-jar",
        "//external:log4j-api-jar",
        "//external:log4j-core-jar",
        "//external:log4j-slf4j-impl-jar",
        "//external:maven-model-jar",
        "//external:motif-hamcrest-jar",
        "//external:motif-jar",
        "//external:plexus-utils-jar",
        "//external:roaster-api-jar",
        "//external:roaster-jdt-jar",
        "//external:takari-cpsuite-jar",
        "//external:zstd-jni-jar",
    ],
)
